In [2]:
import requests
import json
import requests
from pprint import pprint
import pandas as pd
import gmaps
import matplotlib.pyplot as plt

In [3]:
# Store filepath in a variable
census_file = "Census_Data_v3.csv"
census_data = pd.read_csv(census_file, encoding="ISO-8859-1")
census_data

,Unnamed: 0,ZIP,City,State,Latitude,Longitude,County,Median Income,Population
0,0,31150,Atlanta,GA,33.844371,-84.474050,Fulton County,NaN,NaN
1,1,31646,Saint George,GA,30.518903,-82.080630,Washington County,NaN,NaN
2,2,31826,Shiloh,GA,32.803518,-84.693840,Hardin County,22196.0,2238.0
3,3,30334,Atlanta,GA,33.702657,-84.439127,Fulton County,-666666666.0,0.0
4,4,31606,Valdosta,GA,30.802411,-83.196240,Lowndes County,24773.0,3543.0
...,...,...,...,...,...,...,...,...,...
990,990,31402,Savannah,GA,31.971394,-81.071560,Chatham County,NaN,NaN
991,991,30152,Kennesaw,GA,34.002147,-84.633920,Cobb County,39777.0,43310.0
992,992,30655,Monroe,GA,33.786041,-83.699010,Ouachita Parish,26088.0,25210.0
993,993,30376,Atlanta,GA,33.844371,-84.474050,Fulton County,NaN,NaN
994,994,31038,Hillsboro,GA,33.172786,-83.635540,Washington County,28059.0,566.0

In [19]:
# delete NaN records from Census Data
new_data1 = census_data.dropna()

# delete median income less than 0
new_data = new_data1.drop(new_data1[new_data1["Median Income"] < 0].index)
new_data

,Unnamed: 0,ZIP,City,State,Latitude,Longitude,County,Median Income,Population
2,2,31826,Shiloh,GA,32.803518,-84.69384,Hardin County,22196.0,2238.0
4,4,31606,Valdosta,GA,30.802411,-83.19624,Lowndes County,24773.0,3543.0
7,7,30531,Cornelia,GA,34.514215,-83.54118,Habersham County,25113.0,10818.0
8,8,30746,Sugar Valley,GA,34.574804,-85.02482,Gordon County,21581.0,940.0
9,9,30415,Brooklet,GA,32.345600,-81.62339,Bulloch County,30633.0,6161.0
...,...,...,...,...,...,...,...,...,...
987,987,30134,Douglasville,GA,33.769636,-84.74967,Douglas County,26846.0,44114.0
988,988,30455,Rocky Ford,GA,32.697762,-81.81036,Otero County,22095.0,465.0
991,991,30152,Kennesaw,GA,34.002147,-84.63392,Cobb County,39777.0,43310.0
992,992,30655,Monroe,GA,33.786041,-83.69901,Ouachita Parish,26088.0,25210.0
994,994,31038,Hillsboro,GA,33.172786,-83.63554,Washington County,28059.0,566.0

In [20]:
# Get median income and sum the population for each city
median_income = new_data.groupby('City')["Median Income"].median()
print(f"median income {median_income}")
Total_Population = new_data.groupby('City')["Population"].sum()
print(f"Total Population {Total_Population}")

median income City
Abbeville       20880.0
Acworth         33711.5
Adairsville     24570.0
Adel            25632.0
Adrian          19562.0
                 ...
Wrens           18634.0
Wrightsville    20232.0
Yatesville      27000.0
Young Harris    15867.0
Zebulon         31654.0
Name: Median Income, Length: 514, dtype: float64
Total Population City
Abbeville        4563.0
Acworth         99683.0
Adairsville     16138.0
Adel            10836.0
Adrian           3071.0
                 ...
Wrens            3065.0
Wrightsville     7046.0
Yatesville       1656.0
Young Harris     5038.0
Zebulon          4352.0
Name: Population, Length: 514, dtype: float64

In [23]:
Total_Population.sort_values()

City
Sharon               28.0
Tennga               40.0
Seville              43.0
Siloam               67.0
Alston               69.0
                   ...
Augusta          204303.0
Savannah         254069.0
Lawrenceville    256112.0
Marietta         322628.0
Atlanta          988350.0
Name: Population, Length: 514, dtype: float64

In [24]:
# Extract first record from each group
new_data = census_data.groupby('City').first()
city_census_data = new_data.drop(columns = ["Median Income","Population"])
city_census_data

,Unnamed: 0,ZIP,State,Latitude,Longitude,County
City,,,,,,
Abbeville,465,31001,GA,31.972626,-83.33082,Abbeville County
Acworth,313,30102,GA,34.097998,-84.61830,Cobb County
Adairsville,280,30103,GA,34.368647,-84.92452,Bartow County
Adel,673,31620,GA,31.133004,-83.42736,Dallas County
Adrian,733,31002,GA,32.549854,-82.56948,Lenawee County
...,...,...,...,...,...,...
Wrens,75,30833,GA,33.200325,-82.37625,Jefferson County
Wrightsville,155,31096,GA,32.717320,-82.68926,New Hanover County
Yatesville,684,31097,GA,32.912207,-84.14812,Lawrence County
Young Harris,442,30582,GA,34.954638,-83.86484,Towns County
Zebulon,549,30295,GA,33.101705,-84.31252,Wake County

In [25]:
# Add Median Income and Population to city census data
city_census_data["Median Income"]=median_income
city_census_data["Total Population"] = Total_Population
city_census_data

,Unnamed: 0,ZIP,State,Latitude,Longitude,County,Median Income,Total Population
City,,,,,,,,
Abbeville,465,31001,GA,31.972626,-83.33082,Abbeville County,20880.0,4563.0
Acworth,313,30102,GA,34.097998,-84.61830,Cobb County,33711.5,99683.0
Adairsville,280,30103,GA,34.368647,-84.92452,Bartow County,24570.0,16138.0
Adel,673,31620,GA,31.133004,-83.42736,Dallas County,25632.0,10836.0
Adrian,733,31002,GA,32.549854,-82.56948,Lenawee County,19562.0,3071.0
...,...,...,...,...,...,...,...,...
Wrens,75,30833,GA,33.200325,-82.37625,Jefferson County,18634.0,3065.0
Wrightsville,155,31096,GA,32.717320,-82.68926,New Hanover County,20232.0,7046.0
Yatesville,684,31097,GA,32.912207,-84.14812,Lawrence County,27000.0,1656.0
Young Harris,442,30582,GA,34.954638,-83.86484,Towns County,15867.0,5038.0
Zebulon,549,30295,GA,33.101705,-84.31252,Wake County,31654.0,4352.0

In [31]:
# Output to file
city_census_data.to_csv("Resources/Clean_Census_Data.csv", index=True, header=True)